function h = draw_flow_box(ax, pos, labelText, faceColor, edgeColor, varargin)
%DRAW_FLOW_BOX Draw a rounded process box in axes coordinates.
if nargin < 5 || isempty(edgeColor)
    edgeColor = [0.25 0.28 0.31];
end
h = rectangle(ax, 'Position', pos, 'Curvature', 0.08, ...
    'FaceColor', faceColor, 'EdgeColor', edgeColor, 'LineWidth', 1.2);
text(ax, pos(1) + pos(3)/2, pos(2) + pos(4)/2, labelText, ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'Interpreter', 'none', 'FontName', 'Arial', 'FontSize', 9, ...
    'Color', [0.10 0.12 0.14], varargin{:});
end
