function fig = new_figure(cfg, position)
%NEW_FIGURE Create a consistent headless-friendly figure.
if nargin < 2
    position = [80 80 1500 920];
end
fig = figure('Color', 'white', 'Visible', cfg.visible, ...
    'Units', 'pixels', 'Position', position, ...
    'Renderer', cfg.renderer);
% Explicit descendant defaults make exports independent of the user's
% desktop light/dark theme.
set(fig, 'DefaultAxesColor', 'white', ...
    'DefaultAxesXColor', cfg.colors.dark, ...
    'DefaultAxesYColor', cfg.colors.dark, ...
    'DefaultAxesZColor', cfg.colors.dark, ...
    'DefaultTextColor', cfg.colors.dark, ...
    'DefaultLegendColor', 'white', ...
    'DefaultLegendTextColor', cfg.colors.dark, ...
    'DefaultLegendEdgeColor', [0.72 0.74 0.77], ...
    'DefaultColorbarColor', cfg.colors.dark);
end
